language: go
go:
  - 1.8
  - 1.9
  - master

install:
  - wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O dep
  - chmod +x dep
  - ./dep ensure

script: 
  - go build -tags=gingonic